---
- name: Install Docker on Amazon Linux
  hosts: webservers
  become: yes 

  tasks:
    - name: install java
      yum:
        name: java
        state: persent
      
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - docker-compose
        
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

