
---
- name: Install Jenkins
  hosts: all
  become: yes

  tasks:
    - name: Install Java OpenJDK
      yum:
      name: java-1.8.0-openjdk
      state: present

    - name: Add Jenkins APT repository key
      yum_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key

    - name: Add Jenkins APT repository
      yum_repository:
        repo: "deb http://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Update package cache
      yum:
      update_cache: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
      
      
    
