---
- name: Install Docker on Amazon Linux
  hosts: webservers
  become: yes 

  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - docker-compose
