---
- name: Install Git on Amazon Linux
  hosts: webservers
  become: yes  # This allows Ansible to use sudo

  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest

    - name: Install Git
      package:
        name: git
        state: present
